# Generated by Django 3.2.18 on 2025-05-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='type',
            field=models.CharField(choices=[('publique', 'Publique'), ('confidential', 'Confidentielle')], default='public', max_length=20),
        ),
    ]
