# Generated by Django 3.2.18 on 2025-05-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Équipe Générale'), ('admin', 'Comité Exécutif')], default='employee', max_length=10),
        ),
    ]
